#Verification of Central Limit Theorem

#The Central Limit Theorem states that if there is a population with mean=mu and standard deviation=sigma and one draws 
#sufficiently large random samples from the population with replacement, then the distribution of the sample means 
#will be approximately normal. Moreover, mu and sigma can be estimated in a manner explained below.

#Create random population data of reasonable size; values are uniformly distributed between min_value and max_value
pop_size <-100000
min_value <- -100
max_value <- 100
set.seed(101)
population <- runif(pop_size, min = min_value, max = max_value)

#Compute actual mean and standard deviation of the population
mu <- mean(population)
sigma <- sd(population)

#Define sampling mechanism - no. of sampling trials and sample size for each trial
trials = 100
sample_size = 50

#Generate sample statistics - draw a random sample and compute its mean; repeat the procedure for the selected no. of trials
mySample <- numeric(trials)
for (i in c(1:trials)) {
  sample <- sample(population, size = sample_size, replace = TRUE)
  mySample[i] <- mean(sample)
}

#Compute estimates for mean and standard deviation from the data generated by the trials
mu_estimate <- mean(mySample) # mean of sample means is a good estimate for population mean
sigma_sample <- sd(mySample)
sigma_estimate <- sigma_sample*sqrt(sample_size) # standard deviation of sample means is biased and needs to be corrected

#Compare the estimated parameters with the actual ones
result <- data.frame("Population_mean" = mu,
                     "Estimated_mean" = mu_estimate,
                     "Population_sd" = sigma,
                     "Estimated_sd" = sigma_estimate)

print(result)

#Plot densities
plot(density(population)) #should look like a uniform distribution between min_value and max_value defined above
plot(density(mySample)) #should look like a normal distribution although the original population was not normally distributed